Game logic
icebox827/tic-tac-toe pull request #3
Opened 2021-01-19 17:12 UTC by icebox827

- Create the game_logic branch
- Remove mocked logic
- Create game logic

2021-01-19 20:22 UTC, LamiaSristy requested changes
# Status: Change Required. 🔴 

Hello Team @icebox827   and @oxenprogrammer   🙌 

Great work so far and Your game is working smoothly.👏 👏 👏 👏 

However, there are some basic works that remain to get approval and move forward. 🛠️

Please check my points here: 👇

- [x] No `puts/print` and `gets.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

- [ ] The project uses at least two classes (Usually it uses three: Game, Board and Player). The code of the project should be logically divided between classes. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/classes.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))


- [ ] If it's an invalid input - You should inform the player about it and asks for their move again

Please make the changes and ask for a re-review.

Feel free to reach me at @lamiasristy 🙋

2021-01-19 20:24 UTC, LamiaSristy commented on lib/games.rb
> +    @player2_token = if @player1_token == 'X'
No `puts/print` and `gets.chomp` outside `main.rb` file.

2021-01-19 23:31 UTC, BrianSammit requested changes
REQUIRED CHANGES :recycle: 
--------------
Hello team!! :wave: excellent job working on the changes.
However, you have to work on some little changes.

------------------
- [x] when I choose a move that it's already taken it works perfectly but it doesn't tell me what's the problem.
----------------------
Kindly fix this and send it for another review :muscle: 
HAPPY CODING!! 

![MB5W4D](https://user-images.githubusercontent.com/64173189/105106634-42554700-5a84-11eb-9053-0b780696a7fc.gif)

2021-01-20 01:53 UTC, rindrajosia requested changes
**Status: Changes Required**
Hello team,
Great work on the project so far, but we have to make a few more changes to get this milestone Approved. Let me break down the changes for you.
[REQUIRED]
_GAME BEHAVIOR:_
- [ ] If the player chose an occupied position, the game informs the player about it and **asks for their move again.**
- [ ] If the player chose an invalid input, the game informs the player about it and **asks for their move again.**

[REQUIRED]
I_mplementation details_
- [ ] The project uses **at least two classes**. The code of the project should be logically divided between classes. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/classes.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)).
- [ ] DRY rule should be respected. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/dry.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)).

Keep up with the efforts towards this project, you are almost there.
Happy coding!!!!
Rindra Josia

2021-01-20 01:53 UTC, rindrajosia commented on bin/main.rb
> +    unless @board.slice(1, 10).include? ' '
Move this logic in your lib folder like your `win` method.

2021-01-20 01:53 UTC, rindrajosia commented on lib/player.rb
> +    end
Please, find a better way to solve this. Think of DRY code.

2021-01-20 08:41 UTC, mke2111 requested changes
# **STATUS: CHANGES REQUIRED**

## Hey Team, I applaud you all for your tremendous efforts towards this milestone. Keep the energy high.

### **REQUIRED CHANGES:**

- [x] remove the .gitkeep file in the lib folder

- [x] In the PlayerMove class, you need to refactor that conditional statement. Keeping your code dry will ensure that you have the best code practices and as such, you won't need to disable Robocop. This will still help in your next projects. 

- You can have the entire winning combinations in an array say 
` [[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 3, 6], .............]` 
- Then search for any winning combination from the user tokens with methods of your choice. (`.any or .all or .include?`)


Make the changes and submit for another review.

## Cheers!!

**Reach me on slack (Roy Mukuye)**

2021-01-20 08:43 UTC, mke2111 commented on lib/move.rb
> +    if board[1] == player_token and board[2] == player_token and board[3] == player_token
Don't Repeat Yourself.

2021-01-20 16:09 UTC, oxenprogrammer commented on lib/move.rb
> +    if board[1] == player_token and board[2] == player_token and board[3] == player_token
refactored as much as possible

2021-01-20 16:28 UTC, MahmoudBakr23 approved these changes
# **Approved ✔✔**

<hr>

**Great job you've done on this project, congratulations! You can now merge and submit.**

<hr>

## **[OPTIONAL]**
The following will complete your project generally and your game specifically as a professional.

- In your main.rb file, please remove the comment in line 43 and the line 55 so that the game stops asking player 2 for his move twice!
- In upcoming projects, try to make your commits more descriptive and also your pull request body.
- In player.rb file the win? method could be refactored and minimized as a previous TSE suggested earlier, try to refactor it so that you follow DRY rules.

<hr>

Good luck in the next projects and happy coding 👨‍💻💻

2021-01-20 16:56 UTC, merged